# Generated by Django 4.0.6 on 2023-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('C', 'Completed'), ('O', 'On Hold')], default='IP', max_length=2),
        ),
    ]
