# Generated by Django 4.0.6 on 2023-03-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_projectupdate_projectcomment_projectapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='benefits',
            field=models.TextField(blank=True),
        ),
    ]
