# Generated by Django 4.0.6 on 2023-03-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='company',
        ),
    ]
