# Generated by Django 4.0.6 on 2023-03-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_rename_owners_company_employees'),
        ('Jobs', '0002_remove_joblisting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
            preserve_default=False,
        ),
    ]
