# Generated by Django 4.0.6 on 2023-03-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='Category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Project and Product Management', 'Management'), ('Design', 'Design'), ('IT Operations and Infrastructure', 'IT and Security'), ('Sales & Marketing', 'Sales & Marketing'), ('Hardware', 'Hardware'), ('Other', 'Other')], max_length=50),
        ),
    ]
