# Generated by Django 4.0.6 on 2023-03-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_education'),
        ('Jobs', '0005_alter_joblisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='used_in_job_app', to='Users.skill'),
        ),
    ]
