# Generated by Django 4.0.6 on 2023-03-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_jobapplication_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills',
        ),
    ]
