# Generated by Django 4.0.6 on 2023-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_remove_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='ApplicationURL',
            field=models.URLField(default='https://www.google.com'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='MinimumExperience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
