# Generated by Django 4.0.6 on 2023-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_joblisting_numberrecruiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='Experience_Level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry'), ('senior', 'Senior'), ('staff', 'Staff'), ('principal', 'Principal')], max_length=20, null=True),
        ),
    ]
