# Generated by Django 4.0.6 on 2023-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0010_joblisting_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='Experience_Level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('principal', 'Principal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Job_Description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
