# Generated by Django 4.0.6 on 2023-03-10 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0011_alter_joblisting_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Experience_Level',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Principal', 'Principal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Job_Requirements',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('applicant', 'job_listing')},
        ),
    ]
