# Generated by Django 4.0.6 on 2023-03-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0012_jobapplication_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='ApplicationURL',
            field=models.URLField(default='https://www.mycompany.com/applyhere'),
        ),
    ]
