# Generated by Django 4.0.6 on 2023-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0013_alter_joblisting_applicationurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='Category',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Full Stack Development', 'Full Stack Development'), ('Data Science & Analytics', 'Data Science & Analytics'), ('Machine Learning & AI', 'Machine Learning & AI'), ('Product & Project Management', 'Product & Project Management'), ('UI/UX & Graphic Design', 'UI/UX & Graphic Design'), ('IT Operations & Network Engineering', 'IT Operations & Network Engineering'), ('Infrastructure & Security', 'Infrastructure & Security'), ('Site Reliability & DevOps', 'Site Reliability & DevOps'), ('Hardware & Embedded Systems', 'Hardware & Embedded Systems'), ('Sales & Marketing', 'Sales & Marketing'), ('Finance, Accounting, & Operations', 'Finance, Accounting, & Operations'), ('Human Resources & Recruiting', 'Human Resources & Recruiting'), ('Customer Support & Success', 'Customer Support & Success'), ('Other', 'Other')], max_length=50),
        ),
    ]
