# Generated by Django 4.0.6 on 2023-03-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0014_alter_joblisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='Job_Description',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='Job_Requirements',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='Job_Title',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='MinimumExperience',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='NumberRecruiting',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='salary_min',
        ),
    ]
