# Generated by Django 4.0.6 on 2023-03-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0015_remove_joblisting_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='Experience_Level',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='Location',
        ),
    ]
