# Generated by Django 4.0.6 on 2023-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0002_city'),
        ('Jobs', '0016_job_categories_remove_joblisting_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_Level_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='Category',
            field=models.ManyToManyField(to='Jobs.job_categories'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='Location',
            field=models.ManyToManyField(to='Country.city'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='Experience_Level',
            field=models.ManyToManyField(to='Jobs.experience_level_choices'),
        ),
    ]
