# Generated by Django 4.0.6 on 2023-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0017_experience_level_choices_joblisting_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='OtherInfo',
            field=models.ManyToManyField(to='Jobs.job_info'),
        ),
    ]
