# Generated by Django 4.0.6 on 2023-03-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessagingAlerts', '0002_remove_message_thread_id_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageThread',
        ),
    ]
