# Generated by Django 4.0.6 on 2023-03-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessagingAlerts', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
