# Generated by Django 4.0.6 on 2023-03-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessagingAlerts', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
