# Generated by Django 4.0.6 on 2023-02-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Published', models.DateTimeField(auto_created=True)),
                ('Title', models.CharField(max_length=256)),
                ('Text', models.TextField(max_length=16000)),
                ('Newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newspaper.newspaper')),
            ],
        ),
    ]
