# Generated by Django 4.0.6 on 2023-02-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0002_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
