# Generated by Django 4.0.6 on 2023-02-28 00:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Newspaper', '0004_newspaper_logo_article_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_Comments',
            new_name='Article_Comment',
        ),
    ]
