# Generated by Django 4.0.6 on 2023-03-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0006_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Date_Published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
