# Generated by Django 4.0.6 on 2023-03-09 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_customuser_profilepic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Newspaper', '0008_article_comment_article_article_comment_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Upvotes',
            field=models.ManyToManyField(related_name='upvoted_articles', through='Newspaper.ArticleUpvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleupvote',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newspaper.article'),
        ),
        migrations.AddField(
            model_name='articleupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='articleupvote',
            unique_together={('article', 'user')},
        ),
    ]
