# Generated by Django 4.0.6 on 2023-03-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0009_articleupvote_article_upvotes_articleupvote_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.CharField(blank=True, choices=[('Technology & Programming', 'Technology & Programming'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Business & Industry', 'Business & Industry'), ('Opinion & Analysis', 'Opinion & Analysis')], max_length=50),
        ),
    ]
