# Generated by Django 4.0.6 on 2023-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('National', 'National'), ('Friends', 'Friends'), ('Organization', 'Organization')], default='Friends', max_length=15),
        ),
    ]
