# Generated by Django 4.0.6 on 2023-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
