# Generated by Django 4.0.6 on 2023-03-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0003_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Date_Commented',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='Date_Voted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
