# Generated by Django 4.0.6 on 2023-03-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_company_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='StockTicker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
