# Generated by Django 4.0.6 on 2023-03-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_rename_owners_company_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='About',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
