# Generated by Django 4.0.6 on 2023-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_company_lasteditedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Is_University',
            field=models.BooleanField(default=False),
        ),
    ]
