# Generated by Django 4.0.6 on 2023-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_company_is_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Is_University',
        ),
        migrations.AlterField(
            model_name='company',
            name='About',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Shareprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
