# Generated by Django 4.0.6 on 2023-03-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Is_University',
            field=models.BooleanField(default=False),
        ),
    ]
