# Generated by Django 4.0.6 on 2023-03-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_company_is_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Email_Domain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
