# Generated by Django 4.0.6 on 2023-03-13 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0012_company_email_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('About', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('Students', models.IntegerField(blank=True, null=True)),
                ('Website', models.URLField(blank=True)),
                ('Email_Domain', models.CharField(blank=True, max_length=50)),
                ('Employees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('LastEditedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_universities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
