# Generated by Django 4.0.6 on 2023-03-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Is_University',
        ),
    ]
