# Generated by Django 4.0.6 on 2023-03-14 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0014_remove_company_is_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Employees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
