# Generated by Django 4.0.6 on 2023-03-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_alter_university_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Employees',
        ),
        migrations.AddField(
            model_name='company',
            name='Founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Headquarters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
