# Generated by Django 4.0.6 on 2023-03-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_remove_company_employees_company_founded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='Email_Domain',
        ),
        migrations.AddField(
            model_name='company',
            name='Email_Domain',
            field=models.ManyToManyField(blank=True, to='Company.emaildomain'),
        ),
    ]
