# Generated by Django 4.0.6 on 2023-03-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_emaildomain_remove_company_email_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Shareprice',
        ),
    ]
