# Generated by Django 4.0.6 on 2023-03-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_remove_company_shareprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Industry',
            field=models.CharField(blank=True, choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('E_COMMERCE', 'E-commerce'), ('FINTECH', 'Fintech'), ('AI_ML', 'Artificial Intelligence & Machine Learning'), ('CLOUD_SERVICES', 'Cloud Services'), ('DATA_ANALYTICS', 'Data Analytics'), ('CYBER_SECURITY', 'Cybersecurity'), ('GAMING', 'Gaming'), ('IT_SERVICES', 'IT Services'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('BLOCKCHAIN', 'Blockchain'), ('HEALTHTECH', 'Healthtech'), ('EDTECH', 'Edtech'), ('IOT', 'Internet of Things'), ('AR_VR', 'Augmented & Virtual Reality'), ('SOCIAL_MEDIA', 'Social Media')], max_length=100, null=True),
        ),
    ]
