# Generated by Django 4.0.6 on 2023-03-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_alter_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='IsPublic',
            field=models.BooleanField(default=False),
        ),
    ]
