# Generated by Django 4.0.6 on 2023-03-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0021_valuation_notableperson_leadinvestor_fundinground'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valuation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='Company.company'),
        ),
    ]
