# Generated by Django 4.0.6 on 2023-03-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0023_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='user_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
