# Generated by Django 4.0.6 on 2023-03-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0024_companyreview_user_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='future_outlook',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4),
            preserve_default=False,
        ),
    ]
