# Generated by Django 4.0.6 on 2023-03-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0025_companyreview_future_outlook'),
    ]

    operations = [
        migrations.AddField(
            model_name='notableperson',
            name='amount_invested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='notableperson',
            name='investment_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
