# Generated by Django 4.0.6 on 2023-03-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0027_rename_investment_year_notableperson_investment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notableperson',
            old_name='bio',
            new_name='achievements',
        ),
        migrations.RemoveField(
            model_name='notableperson',
            name='amount_invested',
        ),
        migrations.RemoveField(
            model_name='notableperson',
            name='investment_date',
        ),
        migrations.AddField(
            model_name='leadinvestor',
            name='amount_invested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='leadinvestor',
            name='investment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
