# Generated by Django 4.0.6 on 2023-03-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0029_companyedithistory_delete_company_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='LastEditedBy',
        ),
    ]
