# Generated by Django 4.0.6 on 2023-03-16 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0031_rename_culture_and_values_rating_companyreview_culture_and_atmosphere_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonEmployeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('partner', 'Partner'), ('investor', 'Investor'), ('other', 'Other')], max_length=100)),
                ('overall_experience', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('customer_service_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('product_quality_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review_title', models.CharField(blank=True, max_length=200, null=True)),
                ('review_text', models.TextField(max_length=5000)),
                ('advice_to_management', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_employee_reviews', to='Company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
