# Generated by Django 4.0.6 on 2023-03-17 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0033_company_annualprofit_company_annualrevenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='MarketCap',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='StockPrice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_updated_other_fields',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_updated_stockdata',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
