# Generated by Django 4.0.6 on 2023-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0037_alter_company_marketcap_alter_company_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='AnnualProfit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='AnnualRevenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='CashOnHand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='OperatingMargin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='TotalDebt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='TotalLiabilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
