# Generated by Django 4.0.6 on 2023-03-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0038_alter_company_annualprofit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='OperatingMargin',
        ),
    ]
