# Generated by Django 4.0.6 on 2023-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0041_alter_notableperson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
