# Generated by Django 4.0.6 on 2023-02-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Bio',
            field=models.CharField(default='', max_length=240),
        ),
    ]
