# Generated by Django 4.0.6 on 2023-02-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Salary',
            field=models.IntegerField(default=0),
        ),
    ]
