# Generated by Django 4.0.6 on 2023-02-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_shareprice'),
        ('Users', '0003_customuser_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
        ),
    ]
