# Generated by Django 4.0.6 on 2023-03-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_company_review'),
        ('Users', '0007_remove_customuser_following_userfollowing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
        ),
    ]
