# Generated by Django 4.0.6 on 2023-03-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Skills',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('csharp', 'C#'), ('cplus', 'C++'), ('php', 'PHP'), ('javascript', 'JavaScript'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('objective_c', 'Objective-C'), ('go', 'Go'), ('kotlin', 'Kotlin'), ('scala', 'Scala'), ('rust', 'Rust'), ('typescript', 'TypeScript'), ('dart', 'Dart'), ('perl', 'Perl'), ('lua', 'Lua'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('powershell', 'PowerShell'), ('assembly', 'Assembly'), ('matlab', 'MATLAB'), ('r', 'R'), ('swift', 'Swift'), ('visual_basic', 'Visual Basic'), ('delphi', 'Delphi'), ('cobol', 'COBOL'), ('fortran', 'FORTRAN'), ('lisp', 'Lisp'), ('prolog', 'Prolog'), ('scheme', 'Scheme'), ('smalltalk', 'Smalltalk'), ('haskell', 'Haskell'), ('erlang', 'Erlang'), ('fsharp', 'F#'), ('ocaml', 'OCaml'), ('groovy', 'Groovy'), ('perl6', 'Perl 6'), ('crystal', 'Crystal'), ('nim', 'Nim'), ('elixir', 'Elixir'), ('reasonml', 'ReasonML'), ('clojure', 'Clojure'), ('clojurescript', 'ClojureScript'), ('coffeescript', 'CoffeeScript'), ('haxe', 'Haxe'), ('dart', 'Dart'), ('reason', 'Reason'), ('elm', 'Elm'), ('graphql', 'GraphQL'), ('purescript', 'PureScript'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('scala', 'Scala'), ('groovy', 'Groovy'), ('ruby_on_rails', 'Ruby on Rails'), ('django', 'Django'), ('flask', 'Flask'), ('express', 'Express.js'), ('angular', 'AngularJS'), ('react', 'ReactJS'), ('vue', 'Vue.js'), ('ember', 'Ember.js'), ('backbone', 'Backbone.js'), ('meteor', 'Meteor.js'), ('spring', 'Spring Framework'), ('laravel', 'Laravel'), ('codeigniter', 'CodeIgniter'), ('yii', 'Yii'), ('symfony', 'Symfony'), ('cakephp', 'CakePHP'), ('zend', 'Zend'), ('aspnet', 'ASP.NET'), ('nodejs', 'Node.js'), ('nextjs', 'Next.js'), ('gatsbyjs', 'Gatsby.js'), ('nuxtjs', 'Nuxt.js'), ('gridsome', 'Gridsome'), ('strapi', 'Strapi'), ('contentful', 'Contentful'), ('sanity', 'Sanity'), ('prismic', 'Prismic'), ('wordpress', 'WordPress'), ('drupal', 'Drupal'), ('joomla', 'Joomla')], max_length=50, null=True),
        ),
    ]
