# Generated by Django 4.0.6 on 2023-03-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_conversation_customuser_conversations_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='conversations',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
