# Generated by Django 4.0.6 on 2023-03-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0001_initial'),
        ('Users', '0013_remove_message_recipient_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Country',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Country.region'),
        ),
    ]
