# Generated by Django 4.0.6 on 2023-03-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0001_initial'),
        ('Users', '0014_remove_customuser_country_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Country.country'),
        ),
    ]
