# Generated by Django 4.0.6 on 2023-03-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
