# Generated by Django 4.0.6 on 2023-03-10 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_skill_user_skill_customuser_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('degree_type', models.CharField(choices=[('none', 'None'), ('hs', 'High School'), ('aa', 'Associate Degree'), ('ba', "Bachelor's Degree"), ('ma', "Master's Degree"), ('phd', 'Doctorate'), ('other', 'Other')], default='none', max_length=10)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description', models.TextField(blank=True, help_text='Describe your thoughts')),
                ('location', models.CharField(max_length=255)),
                ('activities_awards_and_societies', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
