# Generated by Django 4.0.6 on 2023-03-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('None', 'None'), ('High School', 'High School'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate'), ('Other', 'Other')], default='none', max_length=18),
        ),
    ]
