# Generated by Django 4.0.6 on 2023-03-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_alter_education_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ProfilePicURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
