# Generated by Django 4.0.6 on 2023-03-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_customuser_profilepicurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ProfilePicURL',
        ),
    ]
