# Generated by Django 4.0.6 on 2023-03-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_remove_customuser_profilepicurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
