# Generated by Django 4.0.6 on 2023-03-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_customuser_secondary_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='secondary_email',
        ),
    ]
