# Generated by Django 4.0.6 on 2023-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_remove_customuser_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Company_Verified_Email',
            field=models.BooleanField(default=False),
        ),
    ]
