# Generated by Django 4.0.6 on 2023-03-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_customuser_company_verified_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Company_Verified_Email',
        ),
    ]
