# Generated by Django 4.0.6 on 2023-03-13 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_university'),
        ('Users', '0029_customuser_company_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.university'),
        ),
    ]
