# Generated by Django 4.0.6 on 2023-03-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_alter_education_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.JSONField(default=dict),
        ),
    ]
