# Generated by Django 4.0.6 on 2023-03-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0031_customuser_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_skill',
            name='projects',
        ),
    ]
