# Generated by Django 4.0.6 on 2023-03-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0032_remove_user_skill_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience_level',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Principal', 'Principal')], default='Principal', max_length=50),
        ),
    ]
