# Generated by Django 4.0.6 on 2023-03-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0033_customuser_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
